### ISSUE TITLE
Pimatic-filter errors not solved

### ISSUE THREAD

**Issue by edautz** [mwittig/pimatic-filter#2] opened 2015-12-05 13:18 UTC
I did a upgrade to pimatic-filter 0.8.4 upgrade and changed the type of the mysensors devices to number.

```
{
  "id": "MultiSensorWoonkamer",
  "name": "Multi Sensor Woonkamer",
  "class": "MySensorsMulti",
  "attributes": [
    {
      "name": "Vochtigheid",
      "nodeid": 9,
      "sensorid": 0,
      "type": "number",
      "acronym": "Vochtigheid: ",
      "unit": "%"
    },
    {
      "name": "Temperatuur",
      "nodeid": 9,
      "sensorid": 1,
      "type": "number",
      "acronym": "Temperatuur: ",
      "unit": "Â°C"
    },
    {
      "name": "Druk",
      "nodeid": 9,
      "sensorid": 2,
      "sensortype": 4,
      "type": "number",
      "acronym": "Druk: ",
      "unit": "hPa"
    },
    {
      "name": "LichtsterkteSensor",
      "nodeid": 9,
      "sensorid": 3,
      "type": "number",
      "acronym": "Lichtsterkte: ",
      "unit": "Lux"
    },
    {
      "name": "Voorspelling",
      "nodeid": 9,
      "sensorid": 2,
      "sensortype": 5,
      "type": "string",
      "acronym": "Voorspelling: "
    }
  ]
},
{
  "id": "MultiSensorWoonkamerVochtigheidFilter",
  "name": "Multi SensorWoonkamer Vochtigheid Filter",
  "class": "SimpleTruncatedMeanFilter",
  "output": {
    "name": "Vochtigheid",
    "expression": "$MultiSensorWoonkamer.Vochtigheid",
    "acronym": "Vochtigheid: ",
    "type": "number",
    "unit": "%"
  }
},
{
  "id": "MultiSensorWoonkamerTemperatuurFilter",
  "name": "Multi SensorWoonkamer Temperatuur Filter",
  "class": "SimpleTruncatedMeanFilter",
  "output": {
    "name": "Vochtigheid",
    "expression": "$MultiSensorWoonkamer.Temperatuur",
    "acronym": "Temperatuur: ",
    "type": "number",
    "unit": "Â°C"
  }
},
{
  "id": "MultiSensorWoonkamerDrukFilter",
  "name": "Multi SensorWoonkamer Druk Filter",
  "class": "SimpleTruncatedMeanFilter",
  "output": {
    "name": "Druk",
    "expression": "$MultiSensorWoonkamer.Temperatuur",
    "acronym": "Druk: ",
    "type": "number",
    "unit": "hPa"
  }
},
{
  "id": "MultiSensorWoonkamerLichtsterkteSensorFilter",
  "name": "Multi SensorWoonkamer LichtsterkteSensor Filter",
  "class": "SimpleTruncatedMeanFilter",
  "output": {
    "name": "Druk",
    "expression": "$MultiSensorWoonkamer.LichtsterkteSensor",
    "acronym": "Lichtsterkte: ",
    "type": "number",
    "unit": "Lux"
  }
},
```

But the errors remain.

error [pimatic-filter]: Error on device MultiSensorWoonkamerLichtsterkteSensorFilter: Could not parse expression
14:05:42error [pimatic-filter]: Error on device MultiSensorWoonkamerDrukFilter: Could not parse expression
14:05:42error [pimatic-filter]: Error on device MultiSensorWoonkamerTemperatuurFilter: Could not parse expression
14:05:42error [pimatic-filter]: Error on device MultiSensorWoonkamerVochtigheidFilter: Could not parse expression

and

warn [pimatic]: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
14:17:29error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
14:16:46warn [pimatic]: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
14:16:46error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
14:11:06warn [pimatic]: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
14:11:06error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
14:11:03warn [pimatic]: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
14:11:02error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment] 2015-12-05 13:27
Sorry about this. I'll look into this asap

**Comment by mwittig** [comment] 2015-12-05 13:32
I am getting the following exception. are getting this too? Most likely, it is a problem with pimatic-mysensors. Are you using the latest version of pimatic-mysensors?

```
14:27:50.908 [pimatic] Error loading device MultiSensorWoonkamerDrukFilter: Method getVochtigheid of Multi SensorWoonkamer Druk Filter does not exist!
14:27:50.953 [pimatic] AssertionError: Method getVochtigheid of Multi SensorWoonkamer Druk Filter does not exist!
14:27:50.953 [pimatic]>    at SimpleTruncatedMeanFilter.Device.getUpdatedAttributeValue (c:\Users\marcus\Documents\Devel\PIDEV\pimatic-dev\node_modules\pimatic\lib\devices.coffee:135:7)
```

**Comment by mwittig** [comment] 2015-12-05 13:46
I didn't notice pimatic-mysensors implements its own interpretation of attribute type which different from the rest of pimatic. So, please change "Multi Sensor Woonkamer" attribute type back to what you had before. Following this, the TypeError exception should disappear. Please give a try.

**Comment by edautz** [comment] 2015-12-05 14:08
Sorry but problem not solved.

When starting pimatic the errors begin:

14:52:45.020 [pimatic] info: New device "Multi SensorWoonkamer Vochtigheid Filte                          r"...
14:52:45.177 [pimatic] info: New device "Multi SensorWoonkamer Temperatuur Filte                          r"...
14:52:45.430 [pimatic] info: New device "Multi SensorWoonkamer Druk Filter"...
14:52:45.474 [pimatic] error: Error loading device MultiSensorWoonkamerDrukFilte                          r: Property 'getVochtigheid' of object #<SimpleTruncatedMeanFilter> is not a fun                          ction
14:52:48.539 [pimatic] info: New device "Multi SensorWoonkamer LichtsterkteSenso                          r Filter"...
14:52:48.554 [pimatic] error: Error loading device MultiSensorWoonkamerLichtster                          kteSensorFilter: Property 'getVochtigheid' of object #<SimpleTruncatedMeanFilter                          > is not a function

and 

error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
15:03:13error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
15:02:51error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
14:59:04error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined at SimpleTruncatedMeanFilter.Device.toJson (/usr/local/pimatic-app/node_modules/pimatic/lib/devices.coffee:172:30) at Framework.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:37) at Namespace.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic/lib/framework.coffee:492:35) at Namespace.EventEmitter.emit (events.js:95:17) at Namespace.emit (/usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10) at /usr/local/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!
14:52:48error [pimatic]: Error loading device MultiSensorWoonkamerLichtsterkteSensorFilter: Property 'getVochtigheid' of object #<SimpleTruncatedMeanFilter> is not a function
14:52:45error [pimatic]: Error loading device MultiSensorWoonkamerDrukFilter: Property 'getVochtigheid' of object #<SimpleTruncatedMeanFilter> is not a function

**Comment by edautz** [comment] 2015-12-05 14:12
I am using version 0.8.23 version of mysensors plugin and version 0.8.91 of pimatic

**Comment by edautz** [comment] 2015-12-09 21:24
You said that you couldn't reproduce the problem. Is it sn option to send me your working configuration? Then i can test it with my setup.  

Thnxs in advance.

**Comment by sgoetze** [comment] 2016-02-17 15:04
I have the same issue with the newest version of pimatic (update yesterday) and the filter plugin installed yesterday too.

The logged error is

> error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'value' of undefined
>     at SimpleTruncatedMeanFilter.Device.toJson (/home/pi/pimatic-app/node_modules/pimatic/lib/devices.coffee:173:30)
>     at Framework.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:524:37)
>     at Namespace.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:524:35)
>     at Namespace.EventEmitter.emit (events.js:95:17)
>     at Namespace.emit (/home/pi/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:205:10)
>     at /home/pi/pimatic-app/node_modules/pimatic/node_modules/socket.io/lib/namespace.js:172:14
>     at process._tickCallback (node.js:415:13)
>  This is most probably a bug in pimatic or in a module, please report it!

Here the part of my config.json

```
{
  "id": "nclog",
  "name": "nc-Logauswertung",
  "class": "LogWatcher",
  "file": "/tmp/netcat.log",
  "attributes": [
    {
      "name": "t_a",
      "type": "number",
      "unit": "°C"
    },
    {
      "name": "f_a",
      "type": "number",
      "unit": "%"
    },
    {
      "name": "t_k",
      "type": "number",
      "unit": "°C"
    },
    {
      "name": "f_k",
      "type": "number",
      "unit": "%"
    },
    {
      "name": "l_status",
      "type": "number"
    },
    {
      "name": "tick_gas",
      "type": "number",
      "unit": "l/15 min."
    },
    {
      "name": "zaehler_gas",
      "type": "number",
      "unit": "m³"
    },
    {
      "name": "it",
      "type": "number",
      "unit": "°C"
    },
    {
      "name": "wt",
      "type": "number",
      "unit": "°C"
    },
    {
      "name": "hrt",
      "type": "number",
      "unit": "°C"
    },
    {
      "name": "hrh",
      "type": "number",
      "unit": "%"
    },
    {
      "name": "wzt",
      "type": "number",
      "unit": "°C"
    },
    {
      "name": "wzh",
      "type": "number",
      "unit": "%"
    },
    {
      "name": "baldanwesend",
      "type": "number",
      "unit": "min"
    }
  ],
  "lines": [
    {
      "match": "^K,(.+),(.+),(.+),(.+),(.+)",
      "t_a": "$1"
    },
    {
      "match": "^K,(.+),(.+),(.+),(.+),(.+)",
      "f_a": "$2"
    },
    {
      "match": "^K,(.+),(.+),(.+),(.+),(.+)",
      "t_k": "$3"
    },
    {
      "match": "^K,(.+),(.+),(.+),(.+),(.+)",
      "f_k": "$4"
    },
    {
      "match": "^K,(.+),(.+),(.+),(.+),(.+)",
      "l_status": "$5"
    },
    {
      "match": "^G,(.+),(.+)",
      "tick_gas": "$1"
    },
    {
      "match": "^G,(.+),(.+)",
      "zaehler_gas": "$2"
    },
    {
      "match": "^W1,(.+)",
      "it": "$1"
    },
    {
      "match": "^W2,(.+)",
      "wt": "$1"
    },
    {
      "match": "^W3,(.+),(.+)",
      "hrt": "$1"
    },
    {
      "match": "^W3,(.+),(.+)",
      "hrh": "$2"
    },
    {
      "match": "^W4,(.+),(.+)",
      "wzt": "$1"
    },
    {
      "match": "^W4,(.+),(.+)",
      "wzh": "$2"
    },
    {
      "match": "^A,(.+)",
      "baldanwesend": "$1"
    }
  ]
},
{
  "class": "SimpleTruncatedMeanFilter",
  "id": "filter_hrt",
  "name": "T-Filter Hagen",
  "size": 7,
  "output": {
    "name": "temp",
    "label": "Temperatur",
    "expression": "$nclog.hrt",
    "acronym": "T",
    "type": "number",
    "unit": "°C"
  }
},
{
  "class": "SimpleTruncatedMeanFilter",
  "id": "filter_hrh",
  "name": "H-Filter Hagen",
  "size": 7,
  "output": {
    "name": "hum",
    "label": "Feuchtigkeit",
    "expression": "$nclog.hrh",
    "acronym": "H",
    "type": "number",
    "unit": "%"
  }
},
```

The variables defined by the filter device are not used yet in config.json. The variables used in expression part of the filter device are used in other parts of config.json without any problem. I installed filter plugin because I wanted to replace the directly used variables by mean variables from filter-device. 

I hope that you can reproduce the problem with these informations. Tell me if I can do more. Thank you.

**Comment by mwittig** [comment] 2016-02-18 00:05
@sgoetze Please let me know if the new release solves the issue for you

**Comment by sgoetze** [comment] 2016-02-18 17:11
@mwittig :-) :-) :-)  It works :-) :-) :-) 

I have already changed my config.json to use the mean values. Everything is fine.
Thank you very much.

**Comment by mwittig** [comment] 2016-02-18 20:16
Great! Thanks for the feedback. I am closing this issue now.

**Comment by sgoetze** [comment] 2016-02-19 23:35
@mwittig It works after your last update but there is a non critical error reported when pimatic server is starting up.

I refer to the part of the config.json in one of my posts above. I added the use of the filter variables to config.json with the following part

```
{
  "id": "anzeige_hagenszimmer",
  "name": "Hagens Zimmer",
  "class": "VariablesDevice",
  "variables": [
    {
      "name": "Zimmertemperatur1",
      "expression": "$filter_hrt.temp",
      "unit": "  C",
      "type": "number",
      "label": "Zimmertemperatur1",
      "acronym": "T-innen1"
    },
    {
      "name": "Zimmertemperatur2",
      "expression": "$temperaturHagen.temperature",
      "unit": "  C",
      "type": "number",
      "label": "Zimmertemperatur2",
      "acronym": "T-innen2"
    },
    {
      "name": "Luftfeuchtigkeit",
      "expression": "$filter_hrh.hum",
      "unit": "%",
      "type": "number",
      "label": "Luftfeuchtigkeit",
      "acronym": "H-innen"
    }
  ]
},
```

When pimatic server is starting the following errors are logged

> 22:14:37 error [pimatic]: Error on evaluation of rule condition of rule heizeneinermitteln: Expected variable anzeige_hagenszimmer.Zimmertemperatur1 to have a numeric value. 
> 22:14:37 error [pimatic]: Error on evaluation of rule condition of rule heizeneinermitteln: Expected variable anzeige_hagenszimmer.Zimmertemperatur1 to have a numeric value. 
> 22:14:37 error [pimatic]: Error on evaluation of rule condition of rule temperatursteigterkennen: Expected variable anzeige_hagenszimmer.Zimmertemperatur1 to have a numeric value. 
> 22:14:37 error [pimatic]: Error on evaluation of rule condition of rule temperatursinkterkennen: Expected variable anzeige_hagenszimmer.Zimmertemperatur1 to have a numeric value. 
> 22:14:37 error [pimatic]: Error on evaluation of rule condition of rule tempwohnvorherinit: Expected variable anzeige_hagenszimmer.Zimmertemperatur1 to have a numeric value. 
> 22:14:36 error [pimatic]: rule tempwohnvorherinit error executing an action: Expected variable anzeige_hagenszimmer.Zimmertemperatur1 to have a numeric value. 
> 22:14:36 error [pimatic]: Error updating expression value: Expected variable anzeige_hagenszimmer.Zimmertemperatur1 to have a numeric value. 
> 22:10:52 error [pimatic]: Invalid config of device "filter_hrh": Missing property "discrete" in /output, Property "type" is not a valid property in /output 
> 22:10:51 error [pimatic]: Invalid config of device "filter_hrt": Missing property "discrete" in /output, Property "type" is not a valid property in /output

After these startup errors everything is working fine, no errors anymore. 

It might be a problem with the logWatcher. At pimatic startup values for all variables are in the logfile. But if (1. unsure assumption)  the variables $nclog.hrt and $nclog.hrh stay null after the first run of the logWatcher immediately during startup  the filter devices have no valid values - $filter_hrt.temp and $filter_hrh.hum stay null too. Possibly this produces the first two errors (22:10:51 and 22:10:52). And so - following the chain - even the variables $anzeige_hagenszimmer.Zimmertemperatur1 and $anzeige_hagenszimmer.Luftfeuchtigkeit stay null. 

After some minutes (22:14:36) there is one error I don't know where it comes from. 
All further errors are coming from rules (only the variable $anzeige_hagenszimmer.Zimmertemperatur1 is used, the variable $anzeige_hagenszimmer.Luftfeuchtigkeit is for display and not used in any rule). 

After 5 minutes (2. unsure assumption) pimatic server calls logWatcher again and now the $nclog... variables get values, the filter device can work and gives values for the variables in anzeige_hagenszimmer and everything is fine.

@mwittig I'm not sure if there can anything be changed by you. Possibly you can avoid the first two errors. If a filter has only an input variable with null value it produces null value for the resulting filter variable. No need to generate an error, possibly it could be a warning.

**Comment by mwittig** [comment] 2016-02-20 10:21
@sgoetze  Thanks for the feedback and update!

> 22:10:52 error [pimatic]: Invalid config of device "filter_hrh": Missing property "discrete" in /output, Property "type" is not a valid property in /output 

This is due to shortcomings in the device-config-schema. I'll fix that asap. Regarding the "type" property you can remove that from device configuration. 

> 22:14:37 error [pimatic]: Error on evaluation of rule condition of rule heizeneinermitteln: Expected variable anzeige_hagenszimmer.Zimmertemperatur1 to have a numeric value. 

Need to do more testing to track down the issue.

**Comment by mwittig** [comment] 2016-09-14 18:53
Fixed by the commit https://github.com/mwittig/pimatic-filter/commit/a1eb3bdda4d1e15e808673ac8208b225ab7349de

**Closed as completed by mwittig** 2016-09-14 18:53 UTC
Labels: bug
